version: '3.8'

services:
    bot:
        build: ./bot
        container_name: captain_bot
        restart: always
        network_mode: host

    web: 
        build: ./web
        container_name: captain_web
        restart: always
        network_mode: host