version: '3.3'

services:
    bot:
        build: ./artemis
        container_name: artemis_bot
        depends_on: 
            - dashboard
        restart: always

        network_mode: host

    dashboard: 
        build: ./dashboard
        container_name: artemis_dashboard
        restart: always
        
        ports:
            - 6543:6543
        network_mode: host